### PR TITLE
update LICENSE - fix year, changing to .md file

### PR DESCRIPTION
**Pull request by myzeprog**
# Fixes # 

### Checklist
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guide] and my PR follows them.
- [ ] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- update year in license, rename to .md

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/ruby-http-client?pullRequest=74) <br/>All committers have signed the CLA.

**Comment by kplimack** [comment]
@myzeprog looking past the [other errors that Travis surfaced](https://travis-ci.org/sendgrid/ruby-http-client/builds/435883440?utm_source=github_status&utm_medium=notification), the tests for this repo are still looking for a `license.txt` file, you'll need to update the tests accordingly.

```
  4) Error:
TestClient#test_license_date_is_updated:
Errno::ENOENT: No such file or directory @ rb_sysopen - LICENSE.txt
    /home/travis/build/sendgrid/ruby-http-client/test/test_ruby_http_client.rb:253:in `read'
    /home/travis/build/sendgrid/ruby-http-client/test/test_ruby_http_client.rb:253:in `test_license_date_is_updated'

```

you can test locally by running `bundle exec rake test`

**Comment by myzeprog** [comment]
> @myzeprog looking past the [other errors that Travis surfaced](https://travis-ci.org/sendgrid/ruby-http-client/builds/435883440?utm_source=github_status&utm_medium=notification), the tests for this repo are still looking for a `license.txt` file, you'll need to update the tests accordingly.
> 
> ```
>   4) Error:
> TestClient#test_license_date_is_updated:
> Errno::ENOENT: No such file or directory @ rb_sysopen - LICENSE.txt
>     /home/travis/build/sendgrid/ruby-http-client/test/test_ruby_http_client.rb:253:in `read'
>     /home/travis/build/sendgrid/ruby-http-client/test/test_ruby_http_client.rb:253:in `test_license_date_is_updated'
> ```
> you can test locally by running `bundle exec rake test`

I updated this test, thanks

**Comment by thinkingserious** [comment]
Hello @myzeprog,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
Sorry @myzeprog,

I fixed this before seeing your PR. As you can see, I still gave you Hacktoberfest credit :)

**Pull request closed without merging**
