### PR TITLE
Add a helper returns the response body as a hash

### PR DESCRIPTION
**Pull request by diegoc-am**
I think the body is already a json string, therefore I only created a method to allow it to be hash

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/ruby-http-client?pullRequest=12) <br/>All committers have signed the CLA.

**Comment by diegoc-am** [comment]
Built the gem and ran the tests against sendgrid-ruby, nothing failed

```
sendgrid-ruby git:master ❯ bundle exec rake test                                                                                                             ⏎
/home/diego/.rbenv/versions/2.4.1/bin/ruby -I"lib:test" -I"/home/diego/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-0.9.6/lib" "/home/diego/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-0.9.6/lib/rake/rake_test_loader.rb" "test/sendgrid/test_sendgrid-ruby.rb" "test/sendgrid/helpers/mail/test_category.rb" "test/sendgrid/helpers/mail/test_mail.rb" "test/sendgrid/helpers/mail/test_personalizations.rb" 
Activating Prism (~20 seconds)
Prism started
Run options: --seed 8574

# Running:

................................................................................................................................................................................................................................................................

Finished in 14.516840s, 17.6347 runs/s, 18.3235 assertions/s.

256 runs, 266 assertions, 0 failures, 0 errors, 0 skips
Prism shut down

```

**Comment by diegoc-am** [comment]
I think I've already signed the CLA before

**Comment by thinkingserious** [comment]
Hello @belfazt,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
