### PR TITLE
Create PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by emisanada**
Create a Pull Request Template for `sendgrid/ruby-http-client`.
Issue: https://github.com/sendgrid/ruby-http-client/issues/31

Preview: 
screen shot 2017-10-26 at 19 34 29

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/ruby-http-client?pullRequest=33) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/ruby-http-client?pullRequest=33) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/ruby-http-client?pullRequest=33) it.</sub>

**Comment by mbernier** [comment]
Pending #32

**Comment by mbernier** [comment]
Hey @emisanada if you sign the CLA, I can get this merged. Thanks!

**Comment by mbernier** [comment]
#41 got the CLA signed, so we went ahead and merged that PR.

**Pull request closed without merging**
