### PR TITLE
chore: Missing Dev Dependencies + rubocop  #79

### LINKED ISSUE #79: minitest missing from development dependencies
#### Issue Summary

Minitest is required for running the tests, but it is missing from the gemspec which defines the dependencies for the peoject.

#### Steps to Reproduce

```bash
bundle exec rake test
```

```bash
bundle exec rake test                                                                                                                                             (operations@staging_mdw1/operations)
/Users/jplimack/repos/ruby-http-client/test/test_ruby_http_client.rb:3:in `require': cannot load such file -- minitest/autorun (LoadError)
	from /Users/jplimack/repos/ruby-http-client/test/test_ruby_http_client.rb:3:in `<top (required)>'
	from /Users/jplimack/repos/ruby-http-client/vendor/ruby/2.3.0/gems/rake-0.9.6/lib/rake/rake_test_loader.rb:10:in `require'
	from /Users/jplimack/repos/ruby-http-client/vendor/ruby/2.3.0/gems/rake-0.9.6/lib/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
	from /Users/jplimack/repos/ruby-http-client/vendor/ruby/2.3.0/gems/rake-0.9.6/lib/rake/rake_test_loader.rb:9:in `each'
	from /Users/jplimack/repos/ruby-http-client/vendor/ruby/2.3.0/gems/rake-0.9.6/lib/rake/rake_test_loader.rb:9:in `block in <main>'
	from /Users/jplimack/repos/ruby-http-client/vendor/ruby/2.3.0/gems/rake-0.9.6/lib/rake/rake_test_loader.rb:4:in `select'
	from /Users/jplimack/repos/ruby-http-client/vendor/ruby/2.3.0/gems/rake-0.9.6/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/Users/jplimack/repos/ruby-http-client/vendor/ruby/2.3.0/gems/rake-0.9.6/lib" "/Users/jplimack/repos/ruby-http-client/vendor/ruby/2.3.0/gems/rake-0.9.6/lib/rake/rake_test_loader.rb" "test/test*.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
```

### PR DESCRIPTION
**Pull request by kplimack**
Signed-off-by: Jake Plimack <jake.plimack@gmail.com>

Resolves #79 

* provides missing gems needed for development ( minitest )
* lints code w/rubocop, provides .rubocop.yml
* expanded Rakefile to drive linting + testing

You can now use the `Rakefile` to drive testing.

```bash
bundle exec rake 
rubocop -c .rubocop.yml
.rubocop.yml: Style/SpaceBeforeFirstArg has the wrong namespace - should be Layout
.rubocop.yml: Style/EmptyLinesAroundBlockBody has the wrong namespace - should be Layout
.rubocop.yml: Style/FileName has the wrong namespace - should be Naming
.rubocop.yml: Style/ExtraSpacing has the wrong namespace - should be Layout
Inspecting 7 files
.......

7 files inspected, no offenses detected
Run options: --seed 54688

# Running:

F....FF.....F.................F

Finished in 0.005653s, 5483.5423 runs/s, 7783.0923 assertions/s.

  1) Failure:
TestClient#test_usage_exists [/Users/jplimack/repos/ruby-http-client/test/test_ruby_http_client.rb:245]:
Expected false to be truthy.

  2) Failure:
TestClient#test_docker_exists [/Users/jplimack/repos/ruby-http-client/test/test_ruby_http_client.rb:189]:
Expected false to be truthy.

  3) Failure:
TestClient#test_docker_compose_exists [/Users/jplimack/repos/ruby-http-client/test/test_ruby_http_client.rb:193]:
Expected false to be truthy.

  4) Failure:
TestClient#test_use_cases_exists [/Users/jplimack/repos/ruby-http-client/test/test_ruby_http_client.rb:249]:
Expected false to be truthy.

  5) Failure:
TestClient#test_license_date_is_updated [/Users/jplimack/repos/ruby-http-client/test/test_ruby_http_client.rb:255]:
Expected: 2018
  Actual: 2017

31 runs, 44 assertions, 5 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/Users/jplimack/repos/ruby-http-client/vendor/ruby/2.3.0/gems/rake-0.9.6/lib" "/Users/jplimack/repos/ruby-http-client/vendor/ruby/2.3.0/gems/rake-0.9.6/lib/rake/rake_test_loader.rb" "test/test*.rb" ]
/Users/jplimack/repos/ruby-http-client/Rakefile:19:in `block in <top (required)>'
/Users/jplimack/repos/ruby-http-client/Rakefile:28:in `block (2 levels) in <top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @kplimack,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by kplimack** [comment]
Thanks to @tachyons for his help on this!

**Comment by thinkingserious** [comment]
Hello @kplimack,<br /><br/>Thanks again for the PR!<br /><br />                                         We noticed that you have earned 4 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold.<br /><br />                                         Also, please be sure that you have officially registered <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @kplimack,<br /><br/>Thanks again for the PR!<br /><br />                                         You have earned 4 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold or to simply continue the celebration.<br /><br />                                         Also, <strong>please be sure you have officially registered with us <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a> by November 1, 2018</strong> to qualify.<br /><br />                                         If you have any questions you can email us at <a href="mailto:dx+hacktoberfest2018@sendgrid.com">dx+hacktoberfest2018@sendgrid.com</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid

**Pull request merged**
