### PR TITLE
docs: Create PULL_REQUEST_TEMPLATE.md

### LINKED ISSUE #31: Create a PULL_REQUEST_TEMPLATE
#### Issue Summary

We would like to have a template for describing what has changed in the pull request being submitted.

[Github docs on this](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) 

You can use [this file](https://github.com/sendgrid/open-source-library-data-collector/blob/master/.github/PULL_REQUEST_TEMPLATE.md) as an example

### PR DESCRIPTION
**Pull request by flaredragon**
Added descriptive pull request template
Fixes #31

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/ruby-http-client?pullRequest=41) <br/>All committers have signed the CLA.

**Comment by mbernier** [comment]
Pending #33 #32

**Comment by flaredragon** [comment]
If they don't sign the CLA could my get merged today? @mbernier

**Comment by mbernier** [comment]
Done!

**Comment by thinkingserious** [comment]
Hello @flaredragon,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
