### PR TITLE
fix: Mistake on setup http_options for Net::HTTP object when build http

### PR DESCRIPTION
**Pull request by hoangtuanictvn**
# Fixes #

Add http_options when setup Net:HTTP object to fix the mistake from PR #67 

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](https://github.com/sendgrid/ruby-http-client/blob/main/CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://support.sendgrid.com), or create a GitHub Issue in this repository.

### CODE REVIEW

**Comment by hoangtuanictvn** [comment]
Happy new year!
Because of the old date in the license, the Travis CI had failed. If it is possible, I will update the year of the license from 2020 to 2021.

**Review by eshanholtz — APPROVED** [review]
Looks good to me! Thank you so much for the contribution!

**Comment by hoangtuanictvn** [comment]
@eshanholtz 
Thank you,
I am sorry, but would it be possible to change the date in the license?

**Comment by eshanholtz** [comment]
@hoangtuanictvn 

Yup! We're looking to get the license updated across the board today.

**Comment by hoangtuanictvn** [comment]
@eshanholtz 
I have updated the code based on the update of the license.
Because the old implemented in Net:HTTP on ruby versions 2.4, 2.5 and jruby. CI didn't pass with a small error in the test. But don't worry, I fixed it there 4cd4a4d . And I hope that you can review it again.

Thanks a lot!

**Review by JenniferMah — APPROVED** [review]
Hi @hoangtuanictvn everything looks good to me! Thanks for your contribution!

**Comment by hoangtuanictvn** [comment]
Good morning,

I have pushed a PR https://github.com/sendgrid/sendgrid-ruby/pull/455 to add some feature about http_options in the [sendgrid-ruby](https://github.com/sendgrid/sendgrid-ruby) gem. However, the test had failed (https://github.com/sendgrid/sendgrid-ruby/pull/455#issuecomment-757498782) because this PR hasn't released. I am waiting it. So, could you tell me when is it release?

**Pull request merged**
