### PR TITLE
chore: [Closes #56] Fix some rubocop issues

### LINKED ISSUE #56: Bunch of small cleanup tasks -
#### Issue Summary

- Use the new Ruby 1.9 hash syntax. `task :default => :test` Found in Rakefile by rubocop
- Prefer single-quoted strings when you don't need string interpolation or special symbols. OPEN `desc "Run tests"` - Found in Rakefile by rubocop
- Final newline missing. `task :default => :test` - Found in Rakefile by rubocop
- Unnecessary spacing detected. `host =  'https://api.sendgrid.com'` - Found in examples/example.rb by rubocop
- Operator = should be surrounded by a single space. `host =  'https://api.sendgrid.com'` - Found in examples/example.rb by rubocop
- Use && instead of and. `elsif !@request_body and (name.to_s == "post")` - Found in lib/ruby_http_client.rb by rubocop
- Align ) with (. - line 147  - Found in lib/ruby_http_client.rb by rubocop
- Use Hash#key? instead of Hash#has_key?. ` (!@request_headers.has_key?('Content-Type') ||` - Found in lib/ruby_http_client.rb by rubocop
- When using method_missing, define respond_to_missing? and fall back on super. ```
    def method_missing(name, *args, &_block)
      # Capture the version
      if name.to_s == 'version'
        @version = args[0]
        return _ ``` - Found in lib/ruby_http_client.rb by rubocop

- Don't use parentheses around the condition of an if. ```
      if (@request_body &&
          (!@request_headers.has_key?('Content-Type') ||
           @request_headers['Content-Type'] == 'application/json')
      )``` - Found in lib/ruby_http_client.rb by rubocop
- %w-literals should be delimited by [ and ].  `@methods = %w(delete get patch post put)` - Found in lib/ruby_http_client.rb by rubocop
- Prefer single-quoted strings when you don't need string interpolation or special symbols. `elsif !@request_body and (name.to_s == "post")` - Found in lib/ruby_http_client.rb by rubocop
- Add an empty line after magic comments. `lib = File.expand_path('../lib', __FILE__)` - Found in ruby_http_client.gemspec by rubocop

#### Steps to Reproduce

1. Once done, make a PR and wait for the build
2. Codeclimate should not be reporting these issues for these files any longer

### PR DESCRIPTION
**Pull request by lauratpa**
Closes #56 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
Fixing issues reported by ruboocop

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/ruby-http-client?pullRequest=57) <br/>All committers have signed the CLA.

**Comment by thinkingserious** [comment]
@jekuta

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by mbernier** [comment]
@jekuta 

If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/hacktoberfest-follow-up) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@sendgrid-ci

**Comment by thinkingserious** [comment]
Hello @jekuta,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
