### PR TITLE
chore: [Closes #55] Add code coverage reporting to CC

### LINKED ISSUE #55: Add testing support to codeclimate checks
#### Issue Summary

[Code climate](https://codeclimate.com/github/sendgrid/ruby-http-client) has the ability to run tests and monitor them - please add support for this functionality.

### PR DESCRIPTION
**Pull request by lauratpa**
This PR add code coverage reporting and integrates it with code climate.

Closes #55

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
Add code coverage and integration to Code Climate

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/ruby-http-client?pullRequest=58) <br/>All committers have signed the CLA.

**Comment by lauratpa** [comment]
For this PR to work on CI, a maintainer (who has access to cc) needs to add the TEST REPORT ID for this repo in code climate to be available as an environment variable in TRAVIS (CC_TEST_REPORT_ID).

https://docs.codeclimate.com/docs/finding-your-test-coverage-token
https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

**Comment by mbernier** [comment]
I added the variable to the Travis build and asked Travis nicely to rebuild! Let's see what happens.

**Comment by thinkingserious** [comment]
Hello @jekuta,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
