### PR TITLE
feat: add ratelimit support

### PR DESCRIPTION
**Pull request by awj**
# Fixes # 
Partial support for Rate limit handling as described in sendgrid/sendgrid-ruby#119. Adds functionality to assist users in handling rate limiting. Without more feedback on goals for any kind of in-client automatic rate limiting I'm not able to address that any further.

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Add a SendGrid::Response::Ratelimit class to gather up ratelimit-related functionality/behavior
- Expose a Ratelimit instance as a property of SendGrid::Response

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/ruby-http-client?pullRequest=68) <br/>All committers have signed the CLA.

**Comment by awj** [comment]
@thinkingserious Getting back into Hacktoberfest and I can see that this slipped through the cracks from last time. I've merged latest master to it and touched up some style violations, looks like it's good to go!

**Comment by javmorin** [comment]
Encountering this issue as well, would really appreciate official support for the rate limiting behavior so as to mitigate the thundering herd problem which can currently happen.

**Comment by cseeman** [comment]
I'm starting to do some implementation with the Ruby gem and calling out to the SendGrid APIs (specifically subusers and white label) and would really appreciate this feature. Thank you so much for explaining what the  X-RateLimit-Reset number is in your comment @awj 

> The time (in seconds since Unix Epoch) when the rate limit will reset

I was confused on what that number was supposed to represent. I did have one question @awj, why were you setting the '@reset' instance variable and then overwriting it in the next line:
https://github.com/sendgrid/ruby-http-client/pull/68/files#diff-85d68e873667434927113a0b379b8e86R20

**Comment by awj** [comment]
🤦‍♂ that doesn't need to be happening, and looks like some kind of editing oversight on my part. I'll get it touched up.

**Review by childish-sambino — APPROVED** [review]
LGTM

**Comment by thinkingserious** [comment]
Hello @awj,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
